"""Add category to item

Revision ID: 4c5bec9c5b65
Revises: d80425bd1cd9
Create Date: 2026-07-17 23:33:16.981122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5bec9c5b65'
down_revision: Union[str, Sequence[str], None] = 'd80425bd1cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_passports', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_passports', 'category')
    # ### end Alembic commands ###
