"""Add comments and post type

Revision ID: d80425bd1cd9
Revises: b3f183712efc
Create Date: 2026-07-17 23:30:57.076618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80425bd1cd9'
down_revision: Union[str, Sequence[str], None] = 'b3f183712efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS community_comments")
    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_comments_id'), 'community_comments', ['id'], unique=False)
    op.add_column('community_posts', sa.Column('post_type', sa.String(length=20), server_default='Request', nullable=False))
    op.add_column('community_posts', sa.Column('price_or_condition', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_posts', 'price_or_condition')
    op.drop_column('community_posts', 'post_type')
    op.drop_index(op.f('ix_community_comments_id'), table_name='community_comments')
    op.drop_table('community_comments')
    # ### end Alembic commands ###
