"""add_post_fields

Revision ID: e036bceb9b4b
Revises: 4c5bec9c5b65
Create Date: 2026-07-18 00:06:09.877779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e036bceb9b4b'
down_revision: Union[str, Sequence[str], None] = '4c5bec9c5b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_posts', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('community_posts', sa.Column('item_health', sa.Integer(), nullable=True))
    op.add_column('community_posts', sa.Column('item_carbon', sa.Float(), nullable=True))
    op.add_column('community_posts', sa.Column('image_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_posts', 'image_data')
    op.drop_column('community_posts', 'item_carbon')
    op.drop_column('community_posts', 'item_health')
    op.drop_column('community_posts', 'price')
    # ### end Alembic commands ###
